version: "3.7"
services:
#  app:
#     build:
#       context: .
#       dockerfile: ./docker/App.Dockerfile
#    container_name: app
#    volumes:
#      - ./:/var/www/app:cached
#      - /var/www/app/node_modules
#    restart: always
#    ports:
#      - 3001:3001
#    links:
#      - mysql
#      - redis
#    env_file:
#      - docker.env
#   depends_on:
#     - mysql
#     - redis

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - mysql.env

  redis:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
