version: "3.7"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - mysql.env

  redis:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
